export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const SELECT_CLIENT = 'SELECT_CLIENT';
export const UNSELECT_CLIENT = 'UNSELECT_CLIENT';
export const SELECT_DEVICE = 'SELECT_DEVICE';
export const UNSELECT_DEVICE = 'UNSELECT_DEVICE';
export const SELECT_NOTIFICATION = 'SELECT_NOTIFICATION';
export const UNSELECT_NOTIFICATION = 'UNSELECT_NOTIFICATION';
